### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by Luni-4**
- Update CI
- Add a deployment script

### CODE REVIEW

**Comment by shssoichiro** [comment]
The big MR has been merged, this likely could use a rebase. I don't think anything in the build script itself should break, but the deploy script will likely need some tweaks. The big change is that this project is now workspace-based, and there are two binaries, rav1e-by-gop and rav1e-worker.

**Comment by Luni-4** [comment]
Great! Thanks a lot @shssoichiro! :)

I will address that as soon as possible

**Comment by Luni-4** [comment]
@shssoichiro 

It's ready for reviewing

**Review by shssoichiro — APPROVED** [review]
Thanks, looks good to me!

**Pull request merged**
