### PR TITLE
Use rayon

### PR DESCRIPTION
**Pull request by lu-zero**
The locking system seems to have some interesting problems.

### CODE REVIEW

**Comment by shssoichiro** [comment]
Does this have the same general behavior as the old system? What issues were you seeing with the manual locking implementation?

**Comment by shssoichiro** [comment]
@lu-zero ping

**Comment by lu-zero** [comment]
I hadn't had time to debug, but basically the first thread stays paused until the other two are used. I'll try to update the set to use the new channel-api to see if it makes the code simpler as it should.

**Comment by shssoichiro** [comment]
I've possibly caused you some merge conflicts here. Pretty big rework merged into master to support encoding in one-pass using channels.

**Comment by lu-zero** [comment]
yes, I have to redo it ^^;

(also yet another reason to NOT keep Cargo.lock in git).

**Comment by lu-zero** [comment]
Here a little step in the middle, using scoped threads instead of unbounded threads.

**Review by shssoichiro — APPROVED** [review]
Seems reasonable

**Review by shssoichiro — APPROVED** [review]

**Comment by shssoichiro** [comment]
I need to revert the rayon portion of this. It seems that rayon's threadpool is trying to be "helpful", and is actually causing https://github.com/rust-av/rav1e-by-gop/issues/43. I will probably cherry-pick back in the anyhow and crossbeam portions, those seem to be fine.

**Pull request merged**
